### ISSUE TITLE
Define line break

### ISSUE THREAD

**Issue by nichtich** [gordonbrander/subtext#4]
Which character(s) are considered a [line break](https://en.wikipedia.org/wiki/Newline)? LF? Also CRLF? All linebreaks defined by Unicode? I'd not include additional Unciode line breaks such as U+2029 so you can still use them for linebreaks within a block (if you your editor supports entering it instead of a normal line break)

**Comment by gordonbrander** [comment]
This is a great call-out, thank you!

My instinct is to define line breaks in terms of Unix and Windows ASCII newline escape sequences, so: `\n` and `\r\n` at the end of a line would be treated equivalently as a line break.

Combing through https://en.wikipedia.org/wiki/Newline, I notice JSON and JavaScript treat newlines differently. JSON allows `LS` and `PS` in strings, while ECMAScript prior to ES2019 treats them as newlines.

Anyone happen to have links on newline footguns? I'd love to do the most universal thing here, and I want to avoid spec'ing in an edge case that will bite later.

**Comment by gordonbrander** [comment]
Idea from Ade: “Standardise on Unix newlines and follow the Go approach of normalising every file you touch.” https://twitter.com/ade_oshineye/status/1396726639464169474?s=21
